# .readthedocs.yaml

version: 2

# Set the build system to use
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Define the Python environment
python:
  install:
    - requirements: requirements.txt  

# Set the documentation builder
sphinx:
  configuration: docs/conf.py
